/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VIEW;

import DAO.ConexaoDAO;
import DAO.ProdutoDAO;
import DTO.ProdutoDTO;

import java.sql.PreparedStatement;
import java.sql.Connection;
import java.util.Vector;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlos
 */
public class frmCadastroProdutoPAINEL extends javax.swing.JPanel {

    /**
     * Creates new form frmCadastroProdutoVIEW
     */
    public frmCadastroProdutoPAINEL() {
        initComponents();
        listarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        txtQuantidadeProduto = new javax.swing.JTextField();
        txtPrecoCompra = new javax.swing.JTextField();
        txtPrecoVenda = new javax.swing.JTextField();
        txtCodigoProduto = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JToggleButton();
        btnCancelar = new javax.swing.JToggleButton();
        btnVerificar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        btnAlterar = new javax.swing.JToggleButton();
        btnExcluir = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        txtIdProduto = new javax.swing.JTextField();
        btnCarregar = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(916, 762));

        labelTitulo.setFont(new java.awt.Font("Noto Sans Mono CJK HK", 1, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(25, 89, 163));
        labelTitulo.setText("Cadastro de Produtos");

        jLabel1.setFont(new java.awt.Font("Noto Sans CJK HK", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 89, 163));
        jLabel1.setText("Nome do produto:");

        jLabel2.setFont(new java.awt.Font("Noto Sans CJK HK", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 89, 163));
        jLabel2.setText("Quantidade:");

        jLabel3.setFont(new java.awt.Font("Noto Sans CJK HK", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 89, 163));
        jLabel3.setText("Preço de Compra:");

        jLabel4.setFont(new java.awt.Font("Noto Sans CJK HK", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 89, 163));
        jLabel4.setText("Preço de Venda:");

        jLabel5.setFont(new java.awt.Font("Noto Sans CJK HK", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(25, 89, 163));
        jLabel5.setText("Código do Produto:");

        txtNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdutoActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(25, 89, 163));
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(25, 89, 163));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(86, 23));
        btnCancelar.setMinimumSize(new java.awt.Dimension(86, 23));
        btnCancelar.setPreferredSize(new java.awt.Dimension(86, 23));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnVerificar.setBackground(new java.awt.Color(25, 89, 163));
        btnVerificar.setForeground(new java.awt.Color(255, 255, 255));
        btnVerificar.setText("Verificar");
        btnVerificar.setMaximumSize(new java.awt.Dimension(86, 23));
        btnVerificar.setMinimumSize(new java.awt.Dimension(86, 23));
        btnVerificar.setPreferredSize(new java.awt.Dimension(86, 23));
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Quantidade", "Codigo", "Preço Compra", "Preço Venda"
            }
        ));
        jScrollPane1.setViewportView(tabelaProduto);

        btnAlterar.setBackground(new java.awt.Color(25, 89, 163));
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.setMaximumSize(new java.awt.Dimension(86, 23));
        btnAlterar.setMinimumSize(new java.awt.Dimension(86, 23));
        btnAlterar.setPreferredSize(new java.awt.Dimension(86, 23));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(25, 89, 163));
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setMaximumSize(new java.awt.Dimension(86, 23));
        btnExcluir.setMinimumSize(new java.awt.Dimension(86, 23));
        btnExcluir.setPreferredSize(new java.awt.Dimension(86, 23));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Noto Sans Mono CJK HK", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(25, 89, 163));
        jLabel8.setText("ID PRODUTO");

        txtIdProduto.setEnabled(false);
        txtIdProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProdutoActionPerformed(evt);
            }
        });

        btnCarregar.setBackground(new java.awt.Color(25, 89, 163));
        btnCarregar.setForeground(new java.awt.Color(255, 255, 255));
        btnCarregar.setText("Carregar");
        btnCarregar.setMaximumSize(new java.awt.Dimension(86, 23));
        btnCarregar.setMinimumSize(new java.awt.Dimension(86, 23));
        btnCarregar.setPreferredSize(new java.awt.Dimension(86, 23));
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnCadastrar)
                            .addGap(18, 18, 18)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(labelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelTitulo)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdutoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        CadastrarProduto();
        listarValores();
        LimparCampos();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        listarValores();
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        LimparCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        AlterarProduto();
        listarValores();
        LimparCampos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        ExcluirProduto();
        listarValores();
        LimparCampos();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
        CarregarCampos();
    }//GEN-LAST:event_btnCarregarActionPerformed

    private void txtIdProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAlterar;
    private javax.swing.JToggleButton btnCadastrar;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JToggleButton btnCarregar;
    private javax.swing.JToggleButton btnExcluir;
    private javax.swing.JToggleButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTable tabelaProduto;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtIdProduto;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtPrecoCompra;
    private javax.swing.JTextField txtPrecoVenda;
    private javax.swing.JTextField txtQuantidadeProduto;
    // End of variables declaration//GEN-END:variables

    private void listarValores() {

        try {
            ProdutoDAO objprodutodao = new ProdutoDAO();
            DefaultTableModel model = (DefaultTableModel) tabelaProduto.getModel();
            model.setNumRows(0);

            ArrayList<ProdutoDTO> lista = objprodutodao.ListarProduto();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_produto(),
                    lista.get(num).getNome_produto(),
                    lista.get(num).getQuant_produto(),
                    lista.get(num).getCod_produto(),
                    lista.get(num).getValor_compra(),
                    lista.get(num).getValor_venda() 
                });
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar Valores VIEW: " + erro);
        }
    }

    private void CadastrarProduto() {
        String nomeProduto, codigoProduto;
        int quantidadeProduto;
        float valorCompra, valorVenda;

        nomeProduto = txtNomeProduto.getText();
        quantidadeProduto = Integer.parseInt(txtQuantidadeProduto.getText());
        codigoProduto = txtCodigoProduto.getText();
        valorCompra = Float.parseFloat(txtPrecoCompra.getText());
        valorVenda = Float.parseFloat(txtPrecoVenda.getText());

        ProdutoDTO objprodutodto = new ProdutoDTO();
        objprodutodto.setNome_produto(nomeProduto);
        objprodutodto.setQuant_produto(quantidadeProduto);
        objprodutodto.setCod_produto(codigoProduto);
        objprodutodto.setValor_compra(valorCompra);
        objprodutodto.setValor_venda(valorVenda);

        ProdutoDAO objprodutodao = new ProdutoDAO();
        objprodutodao.cadastrarProduto(objprodutodto);
    }

    private void LimparCampos() {
        txtCodigoProduto.setText("");
        txtNomeProduto.setText("");
        txtQuantidadeProduto.setText("");
        txtPrecoCompra.setText("");
        txtPrecoVenda.setText("");
        txtNomeProduto.requestFocus();
    }

    private void CarregarCampos() {
        int setar = tabelaProduto.getSelectedRow();

        txtIdProduto.setText(tabelaProduto.getModel().getValueAt(setar, 0).toString());
        txtNomeProduto.setText(tabelaProduto.getModel().getValueAt(setar, 1).toString());
        txtQuantidadeProduto.setText(tabelaProduto.getModel().getValueAt(setar, 2).toString());
        txtCodigoProduto.setText(tabelaProduto.getModel().getValueAt(setar, 3).toString());
        txtPrecoCompra.setText(tabelaProduto.getModel().getValueAt(setar, 4).toString());
        txtPrecoVenda.setText(tabelaProduto.getModel().getValueAt(setar, 5).toString());
    }

    private void AlterarProduto() {
        int id_produto, quantidadeProduto;
        String nomeProduto, codigoProduto;
        float valorCompra, valorVenda;

        id_produto = Integer.parseInt(txtIdProduto.getText());
        nomeProduto = txtNomeProduto.getText();
        codigoProduto = txtCodigoProduto.getText();
        quantidadeProduto = Integer.parseInt(txtQuantidadeProduto.getText());
        valorCompra = Float.parseFloat(txtPrecoCompra.getText());
        valorVenda = Float.parseFloat(txtPrecoVenda.getText());

        ProdutoDTO objprodutodto = new ProdutoDTO();
        objprodutodto.setId_produto(id_produto);
        objprodutodto.setNome_produto(nomeProduto);
        objprodutodto.setQuant_produto(quantidadeProduto);
        objprodutodto.setCod_produto(codigoProduto);
        objprodutodto.setValor_compra(valorCompra);
        objprodutodto.setValor_venda(valorVenda);

        ProdutoDAO objprodutodao = new ProdutoDAO();
        objprodutodao.alterarProduto(objprodutodto);

    }

    private void ExcluirProduto() {
        int id_produto, quantidadeProduto;
        String nomeProduto, codigoProduto;
        float valorCompra, valorVenda;

        id_produto = Integer.parseInt(txtIdProduto.getText());
        nomeProduto = txtNomeProduto.getText();
        codigoProduto = txtCodigoProduto.getText();
        quantidadeProduto = Integer.parseInt(txtQuantidadeProduto.getText());
        valorCompra = Float.parseFloat(txtPrecoCompra.getText());
        valorVenda = Float.parseFloat(txtPrecoVenda.getText());

        ProdutoDTO objprodutodto = new ProdutoDTO();
        objprodutodto.setId_produto(id_produto);
        objprodutodto.setNome_produto(nomeProduto);
        objprodutodto.setQuant_produto(quantidadeProduto);
        objprodutodto.setCod_produto(codigoProduto);
        objprodutodto.setValor_compra(valorCompra);
        objprodutodto.setValor_venda(valorVenda);

        ProdutoDAO objprodutodao = new ProdutoDAO();
        objprodutodao.excluirProduto(objprodutodto);
    }

}
