/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VIEW;

import DAO.VendaTotalDAO;
import DTO.VendaTotalDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Caio
 */
public class frmHistoricoVendasPAINEL extends javax.swing.JPanel {

    /**
     * Creates new form frmHistoricoVendasPAINEL
     */
    public frmHistoricoVendasPAINEL() {
        initComponents();
        listarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaHistoricoVendas = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(32767, 32767));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(916, 762));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 89, 163));
        jLabel1.setText("Histórico de Vendas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        tabelaHistoricoVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Form.Pagamento", "Desconto", "Valor Pago", "Subtotal", "Total", "Troco"
            }
        ));
        jScrollPane1.setViewportView(tabelaHistoricoVendas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 130, 800, 440));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaHistoricoVendas;
    // End of variables declaration//GEN-END:variables

    private void listarValores() {

        try {
           VendaTotalDAO objvendatotaldao = new VendaTotalDAO();
            DefaultTableModel model = (DefaultTableModel) tabelaHistoricoVendas.getModel();
            model.setNumRows(0);

            ArrayList<VendaTotalDTO> lista = objvendatotaldao.ListarVendaTotal();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_venda(),
                    lista.get(num).getCliente_venda(),
                    lista.get(num).getForma_pagamento_venda(),
                    lista.get(num).getDesconto_venda(),
                    lista.get(num).getValor_pago_venda(),
                    lista.get(num).getTotal_produto_venda(),
                    lista.get(num).getTotal_venda(),
                    lista.get(num).getTroco_venda()
                    
                });
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar Valores HisotricoVendasPainel: " + erro);
        }
    }
    
}
